name: flutter_quick_nav
description: A quick and easy Flutter navigation utility with fade transitions.
version: 1.0.0

homepage: https://github.com/FaysalChowdhruy/flutter_quick_nav
repository: https://github.com/FaysalChowdhruy/flutter_quick_nav
issue_tracker: https://github.com/FaysalChowdhruy/flutter_quick_nav/issues
documentation: https://pub.dev/documentation/flutter_quick_nav/latest/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
